### ISSUE TITLE
[Generated doc] Do not collapse the list of Types after clicking

### ISSUE THREAD

**Issue by ngocdaothanh** [SDGGiesbrecht/Workspace#368] opened 2019-11-03 22:43 UTC
The list of Types is displayed:

![Screen Shot 2019-11-04 at 9 38 11 am](https://user-images.githubusercontent.com/10095/68093169-09fd3380-fee7-11e9-9e38-1ce9300b4718.png)

After I click on a type, the list is automatically collapsed:

![Screen Shot 2019-11-04 at 9 38 19 am](https://user-images.githubusercontent.com/10095/68093186-2dc07980-fee7-11e9-9681-f21e47acd024.png)

It's not user friendly.

Can you do not collapse the list please?

I think using the old style HTML frames or the modern ReactJS router will fix the problem.

Another feature request:
Please display the list of types by default.

**Comment by SDGGiesbrecht** [comment] 2019-11-03 23:15
That is not supposed to happen. I will look into it.

**Comment by SDGGiesbrecht** [comment] 2019-11-05 03:41
#369 restores the originally intended behaviour; whichever section the page belongs to defaults to being expanded. Moving from a page in one section to a page in another always results in the new section expanding, and the old one contracting, even if you get there by following a link unrelated to the index.

**Comment by SDGGiesbrecht** [comment] 2019-11-06 02:29
Released in 0.25.1.

**Closed by SDGGiesbrecht** 2019-11-06 02:29 UTC
Labels: Bug, Merged, 🇬🇧🇺🇸🇨🇦EN
