### ISSUE TITLE
Purpose & effective usage not clear from documentation

### ISSUE THREAD

**Issue by Jeehut** [SDGGiesbrecht/Workspace#594] opened 2020-09-27 12:23 UTC
### Description

I just read the Docs and also opened some of the links there, but I still don't get the whole picture: What exactly is the purpose of this ... tool? library? package? I don't even understand it's type. It kind of sounds like a command line tool, but then there's a way to include it via SwiftPM and use features in a Swift file. Also, the docs state that this automates management of Swift projects, but which part does it automate? The creation of new ones? Or can it also adjust existing projects to a structure? How does it do that? What best practices does it follow? Does it work with iOS-targeting projects, too? What exactly is considered a "Swift project"?

Just having auto-generated documentation on the classes and commands doesn't really help understand how I can make use of this effectively. For example, you mentioned on the [Swift forums](https://forums.swift.org/t/manually-integrating-swift-packages/40627/2?u=jeehut) that I can use `workspace refresh continuous-integration` but the README points to [this](https://sdggiesbrecht.github.io/Workspace/%F0%9F%87%AC%F0%9F%87%A7EN/Types/ContinuousIntegrationConfiguration/Properties/manage.html) link which doesn't explain what it will do at all. After some search I've found [that](https://sdggiesbrecht.github.io/Workspace/%F0%9F%87%AC%F0%9F%87%A7EN/Tools/workspace/Subcommands/refresh/Subcommands/continuous%E2%80%90integration.html) page in the docs which has some more info (and should be linked in the README IMHO), but again it does not go into any details as for what exactly it will generate. Will it cover building, tests, code coverage, documentation coverage etc. all in one? What if I want to add custom linters or other stuff, do I need to generate things and then adjust them to my needs? How can I then make sure that future changes to Workspace will be easily applicable by re-running those commands? Is there a plugin-type system so I can add my custom changes without affecting the basic configuration?

Of course, people could "just try it out" to see how the tool behaves, but that's another hurdle and I think a README should at least answer the questions as to how I would profit from using this tool as a user. Currently it looks to me like it's a very opinionated set of tools that cover a specific need which is not even documented. So it just feels like I'm adding a dependency that I can't control or understand after reading the README, thus I would not use it. Having a few good full examples in the README would go a long way to explain this tool/package better.

### Availability to Help

I **would like to help** fix it, but **I would need a lot of guidance**.

### Recommended Correction

All in all I think some usage examples are missing. Maybe there should be a blog post (or a series of it) which explain the more general design and use cases this tool covers. I have the feeling it is a potentially amazing tool but can't be used right now due to lack of easy to understand documentation that not only explains how to use it, but also why someone should use it (including its limitations and building trust by explaining why the design is flexible).

**Comment by SDGGiesbrecht** [comment] 2020-09-27 22:32
Thanks for asking. I will answer here quickly, and then think about how to better the actual read‐me. (That could take some time due to more pressing churn caused by the recent release of Swift 5.3.)

> What exactly is the purpose of this ... tool? library? package? I don't even understand it's type. It kind of sounds like a command line tool, but then there's a way to include it via SwiftPM and use features in a Swift file.

Its purpose is to automate all the menial aspects of managing a package from a single place, and to centralize CI‐like validation in a way that can be easily run locally.

1. **The standard and most basic usage** involves simply launching provided scripts as described in steps 2:4 and 3:1 of the `CONTRIBUTING.md` of any project (such as this [here](https://github.com/SDGGiesbrecht/SDGSwift/blob/master/.github/CONTRIBUTING.md#step-2-branch)) which has already integrated Workspace into its standard workflow (and hasn’t customized or disabled the generation of the `CONTRIBUTING.md` file). A developer’s Initial exposure to this project usually comes through contributing to something that uses it, in which case it explains itself. The basic workflow [used to be described in the read‐me as well](https://github.com/SDGGiesbrecht/Workspace/tree/0.20.0#the-workspace-workflow), but I will have to do some digging to find out when and why it was removed. So thanks for reporting this.

2. The [command line tool](https://sdggiesbrecht.github.io/Workspace/🇬🇧EN/Tools/workspace.html) allows more **advanced usage**. The most significant is the initial generation of those scripts for a project, but it also allows executing any task individually, either to speed up a one‐off use, or for those who do not want to use the standard workflow for some reason. The [`workspace refresh continuous‐integration` subcommand](https://sdggiesbrecht.github.io/Workspace/🇬🇧EN/Tools/workspace/Subcommands/refresh/Subcommands/continuous%E2%80%90integration.html) I mentioned in the forums is one such narrowed use case. It will only generate the GitHub actions without touching anything else in the project.

3. The **configuration file** is itself written in Swift, just like a package manifest. [The module has been exposed as a library product](https://sdggiesbrecht.github.io/Workspace/🇬🇧EN/Libraries/WorkspaceConfiguration.html) for two reasons:
    1. To have its documentation generated the same as a library.
    2. Because you can actually import other packages from inside the configuration (see the import in the example [here](https://sdggiesbrecht.github.io/SDGSwift/🇨🇦EN/Extensions/Configuration/Type%20Methods/load(configuration:named:from:linkingAgainst:in:from:at:minimumMacOSVersion:reportProgress:).html)). So as an **extremely advanced use case**, an organization can create a centralized set of defaults by depending on the configuration library of this package and extending the type with a `configureForMyOrganization()` method. Then each individual project’s configuration can simply import that package and call the organization’s method.

All of these use styles are covered by the semantic versioning of releases. (For now, under major version `0`, patches may be additive and minor versions may be breaking. The only thing still stalling major version at `0` is that the configuration system relies on `@_exported`, which is undocumented and has no stability guarantee.)

> Also, the docs state that this automates management of Swift projects, but which part does it automate? The creation of new ones? Or can it also adjust existing projects to a structure?

Each time you use the Refresh script or run the `workspace refresh` command, it will adjust the project to match whatever has been configured. The policy is that the defaults—used by an unconfigured project—should not write into existing files (with a few exceptions such as canonical Unicode normalization of text files). But if `optIntoAllTasks()` is applied to the configuration or individual things are activated, then it will become more aggressive, such as applying the same file header to all files in the repository (updating copyright dates in the process) or applying `swift-format` to Swift sources.

> What best practices does it follow?

These aren’t codified anywhere yet, but in principle are derived from the Unicode specification, swift.org’s API guidelines, swift‐format’s defaults, GitHub’s best practices, etc. Divergence is only made where there is a good reason.

> Does it work with iOS-targeting projects, too? What exactly is considered a "Swift project"?

iOS is fine. There must be a package manifest, since that is the standard way Workspace discovers what is what in the repository. However, to what degree that manifest actually needs to describe the project depends on which tasks you are doing. Whatever is excluded by the package manifest just might not be recognized by some tasks.

Having an Xcode project at the repository root might hijack the `xcodebuild` invocations, but that could be either annoying or useful depending on what you are trying to do. As long is there is a scheme that _looks_ like a package scheme, Workspace won’t care if it’s really something else.

> After some search I've found that page in the docs which has some more info (and should be linked in the README IMHO), but again it does not go into any details as for what exactly it will generate.

Good observation. The documentation has been rearranged since those read‐me links were written. Since the links didn’t go completely dead, they evaded being flagged for update. In the interest of quickly answering your question: It will generate [these GitHub files](https://github.com/SDGGiesbrecht/SDGCornerstone/tree/master/.github/workflows), which do [produce this when run](https://github.com/SDGGiesbrecht/SDGCornerstone/runs/1158636729), (plus‐minus any configuration differences).

> Will it cover building, tests, code coverage, documentation coverage etc. all in one?

Yes.

> What if I want to add custom linters or other stuff, do I need to generate things and then adjust them to my needs?

If you only care about CI, you can simply put them in a separate workflow file of your own. Workspace will leave it alone.

If you also want to integrate them _into_ Workspace, so that Workspace will fetch them automatically for contributors when they just launch the refreshment script, that is what the configuration’s [custom task properties](https://sdggiesbrecht.github.io/Workspace/🇬🇧EN/Types/WorkspaceConfiguration/Properties/customProofreadingTasks.html) are about. There are parallel properties for the refreshment and validation phases.

I mentioned manually adjusting the GitHub action in the forum, because if you don’t plan on using Workspace for anything but setting up the actions, then you may as well just generate them once. After that you can safely delete the workspace‐related phases and uninstall the Workspace tool, because you won’t actually need it anymore.

> How can I then make sure that future changes to Workspace will be easily applicable by re-running those commands?

I am not sure I understand the question. Workspace tries as much as possible to guarantee any subsequent run of the same patch version of Workspace on the same commit of a project will produce the same result. (It’s only things like copyright dates that have to break that guarantee.)

If you are using the standard workflow, you will get a reminder at the end if there is a newer version of Workspace available, but the tool will not update itself. After installing the updated tool on a machine, running `workspace refresh` from the command line may produce a newer, better result.

What I said in the forum only meant that if you check back from time to time, whatever Workspace is doing will correspond to the current the best practice (within a reasonable time frame anyway; there are some pending adjustments right now).

> Is there a plugin-type system so I can add my custom changes without affecting the basic configuration?

Again, I’m not sure exactly what you are asking. The [CustomTask](https://sdggiesbrecht.github.io/Workspace/🇬🇧EN/Types/CustomTask.html) feature I mentioned farther up might be what you are looking for, but then again it might not.

> Currently it looks to me like it's a very opinionated set of tools that cover a specific need which is not even documented.

Admittedly it originated to fulfill a specific internal need for several specific organizations. But it lives in open source in the hopes that it will be useful for others as well. Requests for adjustments or additions will be duly considered, and even if they are deemed out of scope, the intention would still be to at least open up the necessary hooks to enable a third party to provide the feature as an extension, plug‐in, add‐on, etc.

**Comment by Jeehut** [comment] 2020-09-28 19:31
Thank you @SDGGiesbrecht for taking the time to write this thorough answer. I think it's much clearer to me now what the goal of this repo is and after reading your text I also understand why I was so confused: My impression that this covers several things at once seemed to be correct.

I will definitely test it out in one of my next projects and ask any further questions if I have any. I will keep this issue open since you mentioned some outdated or removed documentation, you can feel free to close this as soon as the basic overview is back and maybe some more general documentation was added. I will open more specific issues if I still have questions once I have the time to check this out properly.

**Comment by SDGGiesbrecht** [comment] 2020-10-19 23:57
The read‐me sections that had gone missing have now been restored.

**Closed by SDGGiesbrecht** 2020-10-19 23:57 UTC
Labels: Documentation, Released, 🇬🇧🇺🇸🇨🇦EN
